### PR TITLE
chore: Update Readme file for UI

### PR DESCRIPTION
**Pull request by yomete**
I removed all instances of NextJS and instructions that were specific to NextJS. I also updated to reflect that we now use Create React App.

### CODE REVIEW

**Comment by yomete** [comment]
fyi @manojVivek @monicawoj I updated the readme here to reflect changes to our UI setup.

**Review by monicawoj — APPROVED** [review]
🚀 lgtm - very helpful!

**Comment by manojVivek** [comment]
Should we also add an empty `build` folder inside `web`, to prevent the error that Monica faced when she built the go binary without building the `ui` or is that alright?

**Comment by yomete** [comment]
Alright. I'll add that 👍🏾

**Pull request merged**
