### PR TITLE
area/ui: Update fonts in the UI

### LINKED ISSUE #877: Use roboto mono in flamegraph and use softer color
Mock up 

Normal:

Screenshot 2022-04-05 at 12 17 08

Diff:

Screenshot 2022-04-05 at 12 18 19

### PR DESCRIPTION
**Pull request by yomete**
This PR updates the fonts used in the Parca UI and also uses softer colors for the Icicle graph. 

The Icicle graph and Top table now use the `Roboto Mono` font and I also decided to update the main font being used in the UI to be `Poppins` since that's the font used in the upcoming Parca website redesign.

Resolves #877 

Some screenshots:
image

image

image

image

image

and because it looks so gooood in **light mode**:
image

### CODE REVIEW

**Comment by brancz** [comment]
Gorgeous 😍

**Comment by brancz** [comment]
Perfectly happy with this being a follow up PR, but can we do the coloring differently for light dark mode? The problem with fading the coloring is that in dark mode the red actually ends up looking darker, which indicates it got “more worse”.

**Comment by yomete** [comment]
I see what you mean @brancz. I can play around with a different (but close) shade of colors for the dark mode in this PR.

**Review by monicawoj — APPROVED** [review]
looks good to me!

**Comment by yomete** [comment]
updated the colors now, thoughts @brancz 

image

image

**Comment by brancz** [comment]
Love it!

**Review by brancz — APPROVED** [review]

**Pull request merged**
