### PR TITLE
Create the arrow record directly

### PR DESCRIPTION
**Pull request by thorfour**
Due to historical reasons we were writing the series into a parquet file to sort the rows, to then extract into an arrow record. 

This removes the intermediary sorting step and writes the series directly into arrow records now that FrostDB supports unsorted insertions.

### CODE REVIEW

**Review by metalmatze — APPROVED** [review]
Very nice!

**Comment by asubiotto** [comment]
But frostdb still assumes data is sorted in order to reduce compaction memory usage, won't this break that?

**Comment by thorfour** [comment]
> But frostdb still assumes data is sorted in order to reduce compaction memory usage, won't this break that?

Did you change that recently?

**Comment by asubiotto** [comment]
> > But frostdb still assumes data is sorted in order to reduce compaction memory usage, won't this break that?
> 
> Did you change that recently?

Yes, in https://github.com/polarsignals/frostdb/pull/559 and saw significant memory savings. There are other improvements including removing the sorting writer (https://github.com/polarsignals/frostdb/pull/570) that was killing us with labels compaction. More improvements summarized in https://github.com/polarsignals/polarsignals/issues/2850.

**Pull request closed without merging**
