### PR TITLE
env-local-test.sh: Fix file format and ctlptl link

### PR DESCRIPTION
**Pull request by knrt10**
The above file did not have executable permission so when running `make
dev/setup` it failed.

For `amd64` arch `ctlptl` releases use `arch_uname` in the link. Fixed
it so that file work correctly. For more information check
https://github.com/tilt-dev/ctlptl/releases/tag/v0.5.1

Signed-off-by: Kautilya Tripathi <tripathi.kautilya@gmail.com>

### CODE REVIEW

**Comment by knrt10** [comment]
There is a latest release of [ctlptl](https://github.com/tilt-dev/ctlptl/releases/tag/v0.8.1). If you folks want, can update it on the same PR in a different commit.

**Comment by brancz** [comment]
Nice! Yes please feel free to update!

**Comment by knrt10** [comment]
Updated. Please check.

**Comment by brancz** [comment]
Thank you so much! Lgtm

**Pull request merged**
