### PR TITLE
chore: Separate go/bench action

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

It's taking too much time to run tests when benchmarks are included.

### CODE REVIEW

**Comment by metalmatze** [comment]
Really? Didn't seem like it when it was first introduced. Every benchmark is just run once... 🤔

**Comment by metalmatze** [comment]
Oh, that's local? Cause on CI works just fine and on my Linux machine, they do too. I'll check on my M1.

**Comment by kakkoyun** [comment]
> Oh, that's local? Cause on CI works just fine, and on my Linux machine, they do too. I'll check on my M1.

FWIW this happens on my desktop, AMD64.

**Comment by kakkoyun** [comment]
This is the exact error message:
```
goos: linux
goarch: amd64
pkg: github.com/parca-dev/parca/pkg/metastore
cpu: AMD Ryzen 9 5950X 16-Core Processor
BenchmarkBuildLinesByLocationIDsQuery/1-32  	       1	       769.0 ns/op
BenchmarkBuildLinesByLocationIDsQuery/10-32 	       1	      1710 ns/op
BenchmarkBuildLinesByLocationIDsQuery/100-32         	       1	      2900 ns/op
BenchmarkBuildLinesByLocationIDsQuery/1000-32        	       1	     33689 ns/op
BenchmarkBuildLinesByLocationIDsQuery/10000-32       	       1	    267170 ns/op
BenchmarkBuildLinesByLocationIDsQuery/100000-32      	       1	   2319867 ns/op
BenchmarkBuildLinesByLocationIDsQuery/1000000-32     	       1	  33370352 ns/op
BenchmarkBuildLocationsByIDsQuery/1-32               	       1	      1640 ns/op
BenchmarkBuildLocationsByIDsQuery/10-32              	       1	      1760 ns/op
BenchmarkBuildLocationsByIDsQuery/100-32             	       1	      5940 ns/op
BenchmarkBuildLocationsByIDsQuery/1000-32            	       1	     32589 ns/op
BenchmarkBuildLocationsByIDsQuery/10000-32           	       1	    383516 ns/op
BenchmarkBuildLocationsByIDsQuery/100000-32          	       1	   3248563 ns/op
PASS
ok  	github.com/parca-dev/parca/pkg/metastore	0.436s
goos: linux
goarch: amd64
pkg: github.com/parca-dev/parca/pkg/parca
cpu: AMD Ryzen 9 5950X 16-Core Processor
Benchmark_WriteRaw-32    	       1	 531741818 ns/op	523909248 B/op	 2222926 allocs/op
--- FAIL: BenchmarkValuesAPI
    parca_test.go:159: failed to parse label-set 05d0460efefd339d315812f9506aecc5a5d22200: 1:1: parse error: bad number or duration syntax: "05d0460"
    parca_test.go:159: failed to parse label-set 0603426c0dd45a339e94969ad56ec94ea0b6871f: 1:1: parse error: bad number or duration syntax: "0603426"
    parca_test.go:159: failed to parse label-set 142f684beede8ab8d524ff5e15ca9df1b52566ff: 1:1: parse error: bad number or duration syntax: "142"
    parca_test.go:159: failed to parse label-set 1bd4c41ef940713a3cb21723669adf290901f3c5: 1:1: parse error: bad number or duration syntax: "1"
    parca_test.go:159: failed to parse label-set 28b40c7af8098a66af6ee093b6986b91cad7694d: 1:1: parse error: bad number or duration syntax: "28"
    parca_test.go:159: failed to parse label-set 392467faca2d964441b8226ee48d994ffc70e545: 1:1: parse error: bad number or duration syntax: "392467"
    parca_test.go:159: failed to parse label-set 3bccb8fe08e48d5ea135b1d0f99de0d771dd752f: 1:1: parse error: bad number or duration syntax: "3"
    parca_test.go:159: failed to parse label-set 3bdef03fb393fa1830c95b11c94382427ae2fa60: 1:1: parse error: bad number or duration syntax: "3"
    parca_test.go:159: failed to parse label-set 596b63a006a4386dcab30912d2b54a7a61827b07: 1:1: parse error: bad number or duration syntax: "596"
    parca_test.go:159: failed to parse label-set 5d817452a709ca3a213341555ddcf446ecee37fa: 1:1: parse error: bad number or duration syntax: "5d817452"
    parca_test.go:159: failed to parse label-set 63426b4d796761766c336a45685943375a6278472f7849776c78314b57755f4949507139347775382d2f31614a694b306f387275696355574b4c364c6e2d2f4e634d3268726f7236594c34557a4745484d6b34: 1:1: parse error: bad number or duration syntax: "63426"
    parca_test.go:159: failed to parse label-set 7121685d4776f9bb68f506ceac09220735dc8725: 1:1: parse error: bad number or duration syntax: "7121685d4776"
    parca_test.go:159: failed to parse label-set 7dc938362569112855b6086de066cd6a18d1b978: 1:1: parse error: bad number or duration syntax: "7dc"
    parca_test.go:159: failed to parse label-set 7fa8b52fae071a370ba4ca32bf9490a30aff31c4: 1:1: parse error: bad number or duration syntax: "7"
    parca_test.go:159: failed to parse label-set 85766e9d8458b16e9c7ce6e07c712c02b8471dbc: 1:1: parse error: bad number or duration syntax: "85766e9d8458"
    parca_test.go:159: failed to parse label-set 8bf3cb884124273640de797a3e77d86c98434ea4: 1:1: parse error: bad number or duration syntax: "8"
FAIL
exit status 1
```

Regardless of the failure. I think we should separate these tasks. We can have another CI action to ensure they won't go stale.
Just as an example, I ran tests more often to benchmarks.

**Pull request merged**
