### PR TITLE
pkg/storage: Querying flat profiles

### PR DESCRIPTION
**Pull request by metalmatze**
Implement querying the new, more simple, `[]*Sample` from the QueryRange and Query.singleProfile handlers.

For now, we pass a `profileTrees` bool into some structs to decide whether or not to use the new storage or old storage way of representing trees. Eventually, we'll clean it up by removing the profileTree entirely.

### CODE REVIEW

**Comment by metalmatze** [comment]
Benchmarks are looking good. And I already know what to do next for appends to get this even lower than the previous benchmarks.

appends:
```
name        old time/op    new time/op    delta
Appends-24    12.5ms ± 3%    16.8ms ± 1%   ~     (p=0.100 n=3+3)

name        old alloc/op   new alloc/op   delta
Appends-24    6.26MB ± 0%    9.84MB ± 0%   ~     (p=0.100 n=3+3)

name        old allocs/op  new allocs/op  delta
Appends-24      122k ± 0%      140k ± 0%   ~     (p=0.100 n=3+3)
```
iterators: (look at this! :tada: :rocket:)
```
name         old time/op    new time/op    delta
Iterator-24     104µs ± 5%      62µs ± 1%   ~     (p=0.100 n=3+3)

name         old alloc/op   new alloc/op   delta
Iterator-24    28.0kB ± 0%     0.6kB ± 0%   ~     (p=0.100 n=3+3)

name         old allocs/op  new allocs/op  delta
Iterator-24     1.70k ± 0%     0.00k ± 0%   ~     (p=0.100 n=3+3)
```

**Comment by brancz** [comment]
Do we have an idea why appends are slower? I would have expected that due to skipping trees we should be quite a bit faster?

**Comment by metalmatze** [comment]
Most of the time in appends is spent in `makeStacktraceKey` and that's exactly what we're going to tackle next:
https://share.polarsignals.com/9aa74a3/

Most significantly, we didn't update the benchmarks after introducing UUIDs. So what we're really comparing above is profileTrees without UUIDs to the new flat samples with UUIDs too.
Let me provide you with a fairer comparison in a minute.

**Comment by metalmatze** [comment]
tree with UUIDs vs flat with UUIDs
```
name        old time/op    new time/op    delta
Appends-24    14.3ms ± 2%    16.8ms ± 1%   ~     (p=0.100 n=3+3)

name        old alloc/op   new alloc/op   delta
Appends-24    8.98MB ± 0%    9.84MB ± 0%   ~     (p=0.100 n=3+3)

name        old allocs/op  new allocs/op  delta
Appends-24      122k ± 0%      140k ± 0%   ~     (p=0.100 n=3+3)
```

**Review by brancz — APPROVED** [review]
lgtm nice work!

**Pull request merged**
