### PR TITLE
pkg/server: JS bundle files template error fix

### PR DESCRIPTION
**Pull request by manojVivek**
Fixes the syntax error that happens with the js bundle files, while building parca binary.

### CODE REVIEW

**Comment by metalmatze** [comment]
oh, this is a fix for 
```
level=error name=parca ts=2022-02-14T14:26:34.219315931Z caller=main.go:58 msg="Program exited with error" err="failed to walk ui filesystem: failed to parse ui file _next/static/chunks/31-40bd58c58f530f0c.js: template: _next/static/chunks/31-40bd58c58f530f0c.js:1: function \"date\" not defined"
```
that I just encountered?

**Review by metalmatze — APPROVED** [review]
Works like a charm!

**Comment by manojVivek** [comment]
Unfortunately, this doesn't work with the NextJs build, as the `{{.Version}}` is in the js bundle. 🤕  But this works with the CRA app. 

I'll check what can be done for this.

**Comment by manojVivek** [comment]
@metalmatze A made another PR for the above issue here: https://github.com/parca-dev/parca/pull/635

Please review at your convenience.

**Pull request merged**
