### PR TITLE
pkg: Use new grpc.NewClient over grpc.Dial

### PR DESCRIPTION
**Pull request by metalmatze**
- **pkg: Use newer grpc.NewClient over deprecated grpc.Dial**
- **Update deprecated golanglint-ci config**

### CODE REVIEW

**Comment by asubiotto** [comment]
Can you add an explanation of why these changes were made to the commit message? I'm not sure what's going on without context.

**Comment by asubiotto** [comment]
This answers my question: https://github.com/grpc/grpc-go/issues/1786

**Review by asubiotto — APPROVED** [review]

**Comment by asubiotto** [comment]
One thing though: shouldn't these lint issues be caught on PR CI? i.e. when the grpc package was upgraded

**Comment by metalmatze** [comment]
> One thing though: shouldn't these lint issues be caught on PR CI? i.e. when the grpc package was upgraded

That's an excellent question. It should indeed have caught it... 
It seems like the action as skipped: https://github.com/parca-dev/parca/actions/runs/9236652064/job/25412732712

**Comment by metalmatze** [comment]
If I understand this config correctly, we can add `go.mod` to this array?
https://github.com/parca-dev/parca/blob/7ff555c749a8bac2ef9a13b64923245bc4d4964c/.github/workflows/go-lint.yml#L42-L48

**Comment by asubiotto** [comment]
I think we can

**Pull request merged**
