### PR TITLE
ui: Updated code formatting

### PR DESCRIPTION
**Pull request by manojVivek**
- Tweaked the `prettier` config as required.
- Ran the formatter for existing files.
- Configured git hook to format the files before a commit using `husky` & `lint-staged`.

Please review commits https://github.com/parca-dev/parca/pull/521/commits/ccbcae4d79baca71bb87ff898cbdea9baf70cd9e, https://github.com/parca-dev/parca/pull/521/commits/b997714919f371e24142aa72d6a15a53954b5b1b, https://github.com/parca-dev/parca/pull/521/commits/e8a6693be098a346f71ac091e203e90922ebaef1 and https://github.com/parca-dev/parca/pull/521/commits/f993f0c15a029d5ba2f1006bf2a2bb558d635d59 for important changes, the other commit is just all files formatted to the new style.

### CODE REVIEW

**Comment by brancz** [comment]
lgtm but looks like we need to fix a number of violations to the newly introduced rules to make CI happy

**Comment by manojVivek** [comment]
> lgtm but looks like we need to fix a number of violations to the newly introduced rules to make CI happy

@brancz Yeah, I'm working on it right now. These changes broke the linter for some reason.

**Comment by brancz** [comment]
The protobuf job fails because it generates those javascript files, either we need to run the prettifier after generating or exclude those files from prettifying, I think I'd prefer the latter as we might get into weird situations formatting the generated code but don't feel strongly about it.

**Comment by manojVivek** [comment]
> I think I'd prefer the latter as we might get into weird situations formatting the generated code but don't feel strongly about it.

Thanks, @brancz. I just did that. 
But during the process, I just failed trying to figure out the protobuf command that generates the ts/js code files. Maybe I should make this an item for the next office hours session, getting more insights into the existing tooling.

**Review by brancz — APPROVED** [review]
Love it!

**Comment by yomete** [comment]
Thanks for working on this! @manojVivek

**Pull request merged**
