### PR TITLE
prefix the frostdb metrics

### PR DESCRIPTION
**Pull request by thorfour**

### CODE REVIEW

**Review by brancz — APPROVED** [review]

**Comment by brancz** [comment]
Should this perhaps happen on the FrostDB side instead?

**Comment by thorfour** [comment]
> 

We could. I've always felt the library shouldn't assume a namespace of the application using it.

**Comment by brancz** [comment]
hmm I don't think I agree with that, that means that frostdb can't have docs of it's own or dashboards that would work regardless of the consumer

**Comment by metalmatze** [comment]
Yep. I agree with Frederic on this one. All metrics coming from the FrostDB repository should have the frostdb prefix. If, Parca wants to, we could prefix them again, making them `parca_frostdb_wal...`, for example.

**Pull request merged**
