### PR TITLE
Update FrostDB for Parca

### PR DESCRIPTION
**Pull request by metalmatze**
Changes: https://github.com/polarsignals/frostdb/compare/571b4dc57775...42eb27a93c4b

### CODE REVIEW

**Review by brancz — APPROVED** [review]

**Review by kakkoyun — COMMENTED** [review]
It seems like something wrong with the deps.

**Comment by metalmatze** [comment]
Since it was approved before and only rebased and force pushed, I enabled auto-merge :relaxed:

**Review by kakkoyun — APPROVED** [review]

**Comment by maxbrunet** [comment]
FYI For simple updates like this one, you can check the box in the dependency dashboard and Renovate will take care of creating the PR and getting it merged

**Comment by metalmatze** [comment]
> FYI For simple updates like this one, you can check the box in the dependency dashboard and Renovate will take care of creating the PR and getting it merged

Nice. That's really good to know!
This one seems easier on the surface than it really was. I needed to update this locally and then also locally try if everything works! :relaxed: In the end, it was still broken... :joy:

**Comment by metalmatze** [comment]
[This issue](https://github.com/parca-dev/parca/issues/1226) is the "dependency dashboard"? Never used Renovate in-depth so I'm still learning about its features.

**Comment by maxbrunet** [comment]
> I needed to update this locally and then also locally try if everything works! :relaxed: In the end, it was still broken... :joy:

In ideal world, we should capture that in CI tests, easier said then done tho, maybe an step-by-step issue or doc would be a start

> [This issue](https://github.com/parca-dev/parca/issues/1226) is the "dependency dashboard"? Never used Renovate in-depth so I'm still learning about its features.

Yep! You can pin the issue if you want, so you always have it handy at the top

**Pull request merged**
