### PR TITLE
chore: prepare dependencies for Renovate

### PR DESCRIPTION
**Pull request by maxbrunet**
Similar to parca-dev/parca-agent#485

And:
* Add `.go-version` file (double usage: GH Actions and version managers)
* Add `.node-version` file (double usage: GH Actions and `nodenv`, consistent name with `.go-version`)
* Add `.nvmrc` because `nvm` is more popular than `nodenv` and it does not cost more
* Remove Alpine version from `golang` and `node` container images. Only the language version is important and the digest is pinned so we should notice if an update causes an issue
* Downgrade `node` container image to match version used in CI

### CODE REVIEW

**Comment by maxbrunet** [comment]
This does not seem related to my changes, only because the workflow is triggered

```diff
buf generate
diff --git a/proto/buf.lock b/proto/buf.lock
index ba73ab0..dc85128 100644
--- a/proto/buf.lock
+++ b/proto/buf.lock
@@ -4,7 +4,7 @@ deps:
   - remote: buf.build
     owner: googleapis
     repository: googleapis
-    commit: 1068d85d09894f7587a3236f489c0d80
+    commit: 8f04c867ddf14e13a231d5119b8ebb8b
   - remote: buf.build
     owner: grpc-ecosystem
     repository: grpc-gateway
Error: Process completed with exit code 1.
```

**Review by kakkoyun — APPROVED** [review]
LGTM :100:

**Comment by kakkoyun** [comment]
> This does not seem related to my changes, only because the workflow is triggered
> 
> ```diff
> buf generate
> diff --git a/proto/buf.lock b/proto/buf.lock
> index ba73ab0..dc85128 100644
> --- a/proto/buf.lock
> +++ b/proto/buf.lock
> @@ -4,7 +4,7 @@ deps:
>    - remote: buf.build
>      owner: googleapis
>      repository: googleapis
> -    commit: 1068d85d09894f7587a3236f489c0d80
> +    commit: 8f04c867ddf14e13a231d5119b8ebb8b
>    - remote: buf.build
>      owner: grpc-ecosystem
>      repository: grpc-gateway
> Error: Process completed with exit code 1.
> ```

We need to update the buf dependencies. `make proto/all`. It could be handled in this PR or in another one.

**Comment by kakkoyun** [comment]
We need to check if the error is an actual error or a flake. I have run it a couple of times. It seems like something broken.

**Comment by maxbrunet** [comment]
> We need to check if the error is an actual error or a flake. I have run it a couple of times. It seems like something broken.

Yup, I had missed a hard-to-read quoting/line-escape, I have fixed it and rearranged  all the dockerized steps to make them more readable

**Review by kakkoyun — APPROVED** [review]
LGTM :heart: Awesome work @maxbrunet as always! We really appreciate your contributions.

**Pull request merged**
