### PR TITLE
fix ingest validatePprofProfile log

### PR DESCRIPTION
**Pull request by danielqsj**
Fix the log in ingest validatePprofProfile()

### CODE REVIEW

**Review by brancz — APPROVED** [review]
Thank you!!

**Comment by brancz** [comment]
(we'll just need you to sign the CLA, which is really just a one-time DCO)

**Comment by danielqsj** [comment]
> (we'll just need you to sign the CLA, which is really just a one-time DCO, so you don't have to remember to sign-off every git commit)

Done.
@brancz great to see you again here :) . Great project.

**Comment by brancz** [comment]
Hah, I was just thinking the same! Thank you, let me know if I/we can be helpful in any way on your journey with Parca! Also feel free to join the discord server! :)

**Comment by manojVivek** [comment]
@all-contributors Please add @danielqsj for code.

**Pull request merged**
