### PR TITLE
#1656 - add pathprefix to api grpcmux

### PR DESCRIPTION
**Pull request by TomHellier**
This PR allows pathprefix to work with the /API endpoint

### CODE REVIEW

**Comment by brancz** [comment]
I suspect we'll need the same here, and remove the `/targets` suffix https://github.com/parca-dev/parca/blob/20ae91059a27e1b4abd3f28855cda9f85175425b/ui/packages/app/web/src/pages/targets.tsx#L49

**Comment by brancz** [comment]
cc @yomete @manojVivek

**Comment by TomHellier** [comment]
Probably need to update this section as well:
https://github.com/parca-dev/parca/blob/20ae91059a27e1b4abd3f28855cda9f85175425b/ui/packages/app/web/src/components/ui/Navbar.tsx#L21-L22

@brancz  can you clarify what you mean by the /targets suffix?

I will have a look at updating this further in the next few days

**Review by yomete — APPROVED** [review]
LGTM!

**Comment by brancz** [comment]
Awesome, this is exactly what I meant. Thank you so much for the amazing contribution!

**Comment by manojVivek** [comment]
@all-contributors Please add @TomHellier for code.

**Pull request merged**
