### PR TITLE
ui/profile/table: Add visibility dropdown for columns

### PR DESCRIPTION
**Pull request by metalmatze**
- ui/profile/Table: Add dropdown to change column visibility
- ui/component/Table: Make table header sticky

image

### CODE REVIEW

**Comment by metalmatze** [comment]
Did you have a chance to take a look at it, @manojVivek?

**Comment by manojVivek** [comment]
> Did you have a chance to take a look at it, @manojVivek?

Didn't check it yet after the initial look. I'll take a look today and maybe ignore type check for that line if I couldn't resolve it.

**Comment by manojVivek** [comment]
Oh, I just noticed @monicawoj is going to look into this, so I'll defer it to her. Fresh eyes might help.

**Comment by monicawoj** [comment]
> Oh, I just noticed @monicawoj is going to look into this, so I'll defer it to her. Fresh eyes might help.

Apologies for the delay here @metalmatze (I was blocked for the past few days because of CORS errors, so was not able to check this locally). I'm just working on some linter/ts fixes and should be ready to merge soon!

**Review by brancz — APPROVED** [review]
Love it!

**Comment by brancz** [comment]
Perhaps a tiny nit, even on a 4k screen it looks like it's all a bit smashed together. Maybe we can find a shorter name for the % columns?

Screenshot 2023-10-03 at 14 49 25

**Review by manojVivek — APPROVED** [review]
Looking good!

**Comment by monicawoj** [comment]
> Perhaps a tiny nit, even on a 4k screen it looks like it's all a bit smashed together. Maybe we can find a shorter name for the % columns?
> 
> Screenshot 2023-10-03 at 14 49 25

Yeah, I agree that a shorter name would be ideal. Would just "X (%)" suffice you think? As in "Cumulative (%)" instead of "Cumulative (% of total)"?

**Pull request merged**
